# ── Generated by the Frankie Compiler v1.22.3 ─────────────────────────
import math as _math
import sys as _sys
from frankie_stdlib import *

def _blk_fn_1():
    r = range(1, 5 + 1)
    assert_eq(_fk_to_str(r), '1..5', 'ranges print in Frankie syntax')
    assert_eq(_fk_to_vec(r), [1, 2, 3, 4, 5], 'to_vec converts to vector')
    assert_eq(_fk_to_vec(range(1, 3 + 1)), [1, 2, 3], 'to_a works on ranges too')
    assert_true((3 in r), 'include? membership')
    assert_true((not (9 in r)), 'include? rejects outsiders')
    assert_eq(_fk_to_vec(_fk_range_step(range(1, 10 + 1), 3)), [1, 4, 7, 10], 'step strides')
    assert_eq(_fk_sum(range(1, 4 + 1)), 10, 'sum works on ranges')
    assert_eq(_fk_to_vec(range(1, 4)), [1, 2, 3], 'exclusive range')
    grade = None
    _case_2 = 85
    if (_case_2 in range(90, 100 + 1)):
        grade = 'A'
    elif (_case_2 in range(70, 89 + 1)):
        grade = 'B'
    else:
        grade = 'C'
    return assert_eq(grade, 'B', 'case/when matches range membership')
test('first-class ranges', _blk_fn_1)
def _blk_fn_3():
    ParseFailure = _fk_def_error('ParseFailure')
    NetworkDown = _fk_def_error('NetworkDown')
    caught = None
    try:
        raise _fk_make_error('ParseFailure', _fk_to_str('bad token on line 3'))
    except _fk_exc('ParseFailure') as e:
        e = str(e)
        caught = e
    assert_eq(caught, 'bad token on line 3', 'rescue catches the declared type')
    order = None
    try:
        raise _fk_make_error('NetworkDown', _fk_to_str('socket closed'))
    except _fk_exc('ParseFailure') as e:
        e = str(e)
        order = 'wrong'
    except _fk_exc('NetworkDown') as e:
        e = str(e)
        order = 'right'
    assert_eq(order, 'right', 'typed rescue picks the matching clause')
    generic = None
    try:
        raise _fk_make_error('ParseFailure', _fk_to_str('boom'))
    except Exception as e:
        e = str(e)
        generic = e
    assert_eq(generic, 'boom', 'generic rescue still catches typed errors')
    builtin = None
    try:
        raise _fk_make_error('TypeError', _fk_to_str('not a number'))
    except _fk_exc('TypeError') as e:
        e = str(e)
        builtin = 'yes'
    assert_eq(builtin, 'yes', 'builtin types still rescue correctly')
    def _lambda_4():
        raise _fk_make_error('ParseFailure', _fk_to_str('x'))
    return assert_raises_typed(_lambda_4, 'ParseFailure', 'assert_raises_typed knows user types')
test('user-defined error types', _blk_fn_3)
def _blk_fn_5():
    file_write('/tmp/_fk117_mod.fk', 'PI_ISH = 3.14\ndef triple(x)\n  x * 3\nend\n')
    geo = _fk_import('/tmp/_fk117_mod')
    assert_eq(geo.triple(7), 21, 'module function call')
    assert_eq(_fk_attr_or_method(geo, 'PI_ISH'), 3.14, 'module constant access')
    return file_delete('/tmp/_fk117_mod.fk')
test('namespaced imports', _blk_fn_5)
def _blk_fn_6():
    def Point(x, y):
        return {"__type__": "Point", "x": x, "y": y}

    pt = Point(3, 4)
    assert_eq(_fk_attr_or_method(pt, 'x'), 3, 'record field via dot')
    return assert_eq(_fk_attr_or_method(pt, 'y'), 4, 'second field via dot')
test('record dot access', _blk_fn_6)
def _blk_fn_7():
    doubled = parallel_map([1, 2, 3, 4, 5], lambda x: _fk_arith('x', x, '2', 2, '*'), workers=3)
    assert_eq(doubled, [2, 4, 6, 8, 10], 'results come back in order')
    return assert_eq(parallel_map([], lambda x: x, workers=2), [], 'empty vector is fine')
test('parallel_map', _blk_fn_7)
def _blk_fn_8():
    def _spawn_fn_9():
        server = tcp_listen(7917)
        client = _fk_attr_or_method(server, 'accept')
        line = _fk_attr_or_method(client, 'recv_line')
        client.send_line(f"pong: {_fk_to_str(line)}")
        _fk_attr_or_method(client, 'close')
        _fk_attr_or_method(server, 'close')
    _threading.Thread(target=_spawn_fn_9, daemon=True).start()
    sleep(0.3)
    sock = tcp_connect('127.0.0.1', 7917, timeout=5)
    sock.send_line('ping')
    reply = _fk_attr_or_method(sock, 'recv_line')
    _fk_attr_or_method(sock, 'close')
    return assert_eq(reply, 'pong: ping', 'tcp round-trip works')
test('tcp sockets', _blk_fn_8, tags=['network'])
def _blk_fn_10():
    stub('shell', (lambda cmd: {'ok': True, 'stdout': 'fake output', 'exit_code': 0}))
    r = _fk_shell('definitely_not_run')
    assert_eq(_fk_index(r, 'stdout'), 'fake output', 'stubbed shell returns fake data')
    unstub('shell')
    stub('http_get', (lambda url: {'body': 'cached'}))
    fake = http_get('http://example.com')
    assert_eq(_fk_index(fake, 'body'), 'cached', 'stubbed http_get')
    return unstub()
test('stub and unstub', _blk_fn_10)
def _blk_fn_11():
    who = 'Frankie'
    msg = 'Hello, ' + _fk_to_str(who) + '!\n  stay stitched\n'
    assert_match(msg, 'Hello, Frankie!', 'heredoc interpolation')
    return assert_match(msg, '  stay stitched', 'indent stripped to common margin')
test('heredocs still solid', _blk_fn_11)