# ── Generated by the Frankie Compiler v1.22.3 ─────────────────────────
import math as _math
import sys as _sys
from frankie_stdlib import *

print(_fk_to_str('╔══════════════════════════════════════════╗'))
print(_fk_to_str("║       Frankie v1.10 — What's New         ║"))
print(_fk_to_str('╚══════════════════════════════════════════╝'))
print(_fk_to_str(''))
print(_fk_to_str('── 1. String & Vector * Repetition ──'))
print(_fk_to_str(_fk_arith("'ha'", 'ha', '3', 3, '*')))
print(_fk_to_str(_fk_arith("'-'", '-', '40', 40, '*')))
print(_fk_to_str(_fk_arith("'='", '=', '20', 20, '*')))
header = '[ Frankie v1.10 ]'
width = 40
pad = _fk_arith("' '", ' ', '_fk_arith("_fk_arith(\'width\', width, \'len(header)\', len(header), \'-\')", _fk_arith(\'width\', width, \'len(header)\', len(header), \'-\'), \'2\', 2, \'//\')', _fk_arith("_fk_arith('width', width, 'len(header)', len(header), '-')", _fk_arith('width', width, 'len(header)', len(header), '-'), '2', 2, '//'), '*')
print(_fk_to_str(_fk_arith('pad', pad, 'header', header, '+')))
print(_fk_to_str(_fk_arith('[0]', [0], '5', 5, '*')))
print(_fk_to_str(_fk_arith('[None]', [None], '3', 3, '*')))
print(_fk_to_str(_fk_arith('[1, 2]', [1, 2], '3', 3, '*')))
cols = [12, 8, 10]
sep = '+'.join([str(_e) for _e in [_fk_arith("'-'", '-', 'w', w, '*') for w in cols]])
print(_fk_to_str(sep))
print(_fk_to_str(''))
print(_fk_to_str('── 2. Heredoc <<~TEXT ──'))
html = '<article>\n  <h1>Frankie v1.10</h1>\n  <p>Zero dependencies. Proudly procedural.</p>\n</article>\n'
print(_fk_to_str(html))
query = 'SELECT name, dept, salary\nFROM employees\nWHERE salary > 80000\nORDER BY salary DESC\n'
print(_fk_to_str(query))
version = 'v1.10'
banner = '┌─────────────────────────────┐\n│   Frankie ' + _fk_to_str(version) + ' is alive!    │\n└─────────────────────────────┘\n'
print(_fk_to_str(banner))
print(_fk_to_str('── 3. times() standalone ──'))
for i in range(3):
    print(_fk_to_str(f"  method form: {_fk_to_str(i)}"))
for i in range(3):
    print(_fk_to_str(f"  function form: {_fk_to_str(i)}"))
print(_fk_to_str(times(5)))
rows = [{'id': _fk_arith('i', i, '1', 1, '+'), 'active': True} for i in times(4)]
_each_recv_1 = rows
for r in _each_recv_1:
    print(_fk_to_str(f"  row {_fk_to_str(_fk_index(r, 'id'))}"))
else:
    _fk_break_val = _each_recv_1
_each_result_2 = _fk_break_val
_each_result_2
print(_fk_to_str(''))
print(_fk_to_str('── 4. flatten(depth) ──'))
nested = [1, [2, 3], [4, [5, [6, 7]]]]
print(_fk_to_str(_fk_flatten_deep(nested, None)))
print(_fk_to_str(_fk_flatten_deep(nested, 1)))
print(_fk_to_str(_fk_flatten_deep(nested, 2)))
pages = [[1, 2, 3], [4, 5], [6, 7, 8, 9]]
all_ids = _fk_flatten_deep(pages, None)
print(_fk_to_str(f"Total: {_fk_to_str(len(all_ids))} items"))
print(_fk_to_str(''))
print(_fk_to_str('── 5. map_with_index ──'))
langs = ['Ruby', 'Python', 'R', 'Fortran']
numbered = [f"{_fk_to_str(_fk_arith('i', i, '1', 1, '+'))}. {_fk_to_str(lang)}" for i, lang in enumerate(langs)]
_each_recv_3 = numbered
for line in _each_recv_3:
    print(_fk_to_str(f"  {_fk_to_str(line)}"))
else:
    _fk_break_val = _each_recv_3
_each_result_4 = _fk_break_val
_each_result_4
def Config(key, value):
    return {"__type__": "Config", "key": key, "value": value}

keys = ['host', 'port', 'debug']
vals = ['localhost', '3000', 'false']
pairs = [Config(k, _fk_index(vals, i)) for i, k in enumerate(keys)]
_each_recv_5 = pairs
for p in _each_recv_5:
    print(_fk_to_str(f"  {_fk_to_str(_fk_index(p, 'key'))} = {_fk_to_str(_fk_index(p, 'value'))}"))
else:
    _fk_break_val = _each_recv_5
_each_result_6 = _fk_break_val
_each_result_6
print(_fk_to_str(''))
print(_fk_to_str('── 6. pp (pretty-print) ──'))
data = {'server': {'host': 'localhost', 'port': 3000}, 'db': {'path': 'app.db', 'pool': 5}, 'flags': ['debug', 'verbose']}
pp(data)
def Employee(name, dept, salary):
    return {"__type__": "Employee", "name": name, "dept": dept, "salary": salary}

team = [Employee('Alice', 'Engineering', 95000), Employee('Bob', 'Design', 82000)]
_each_recv_7 = team
for e in _each_recv_7:
    pp(e)
else:
    _fk_break_val = _each_recv_7
_each_result_8 = _fk_break_val
_each_result_8
print(_fk_to_str(''))
print(_fk_to_str('── 7. Named rescue without variable ──'))
try:
    x = _fk_arith('1', 1, '0', 0, '//')
except _fk_exc('ZeroDivisionError') as _fk_err:
    print(_fk_to_str('  Caught ZeroDivisionError (no variable needed)'))
try:
    raise RuntimeError(_fk_to_str('deliberate error'))
except _fk_exc('RuntimeError') as _fk_err:
    print(_fk_to_str('  Caught RuntimeError silently'))
print(_fk_to_str(''))
print(_fk_to_str('── 8. String encode / decode ──'))
s = 'hello'
b = (_fk_str_encode(s, "utf-8") if isinstance(s, str) else _fk_str_decode(s, "utf-8"))
print(_fk_to_str(b))
print(_fk_to_str(_fk_str_decode(b, "utf-8")))
print(_fk_to_str((_fk_str_encode('hi', 'utf-8') if isinstance('hi', str) else _fk_str_decode('hi', 'utf-8'))))
print(_fk_to_str(_fk_str_decode([70, 114, 97, 110, 107, 105, 101], "utf-8")))
print(_fk_to_str(''))
print(_fk_to_str('── 9. Exit codes ──'))
print(_fk_to_str('  exit(0)  — success'))
print(_fk_to_str('  exit(1)  — general failure'))
print(_fk_to_str('  exit(42) — custom code, propagated to the shell'))
print(_fk_to_str('  echo $?  — check it after frankiec run script.fk'))
print(_fk_to_str(''))
print(_fk_to_str('── 10. --help ──'))
print(_fk_to_str('  frankiec --help          # full usage'))
print(_fk_to_str('  frankiec run --help      # command-specific help'))
print(_fk_to_str('  frankiec fmt --help'))
print(_fk_to_str('  frankiec docs --help'))
print(_fk_to_str(''))
print(_fk_to_str('v1.10 is alive! 🧟⚡'))