# ── Generated by the Frankie Compiler v1.22.3 ─────────────────────────
import math as _math
import sys as _sys
from frankie_stdlib import *

print(_fk_to_str('╔══════════════════════════════════════════╗'))
print(_fk_to_str("║       Frankie v1.15 — What's New         ║"))
print(_fk_to_str('╚══════════════════════════════════════════╝'))
print(_fk_to_str(''))
print(_fk_to_str('── 1. Ternary operator ──'))
score = 85
grade = ('A' if (score >= 90) else ('B' if (score >= 70) else 'C'))
print(_fk_to_str(f"Score {_fk_to_str(score)} → {_fk_to_str(grade)}"))
n = 1
print(_fk_to_str(f"{_fk_to_str(n)} {_fk_to_str(('item' if (n == 1) else 'items'))}"))
x = (-7)
print(_fk_to_str(('positive' if (x > 0) else ('negative' if (x < 0) else 'zero'))))
print(_fk_to_str(''))
print(_fk_to_str('── 2. Keyword default parameters ──'))
def connect(host, port=5432, ssl=True, timeout=30):
    print(_fk_to_str(f"{_fk_to_str(host)}:{_fk_to_str(port)} ssl={_fk_to_str(ssl)} timeout={_fk_to_str(timeout)}s"))

connect('localhost')
connect('prod.db', port=3306)
connect('prod.db', ssl=False, timeout=10)
print(_fk_to_str(''))
print(_fk_to_str('── 3. Splat multi-assign ──'))
a, b, rest = _fk_unpack_splat([1, 2, 3, 4, 5], 2, 0)
print(_fk_to_str(f"a={_fk_to_str(a)} b={_fk_to_str(b)} rest={_fk_to_str(rest)}"))
first, mid, last = _fk_unpack_splat(['alpha', 'beta', 'gamma', 'delta'], 1, 1)
print(_fk_to_str(f"first={_fk_to_str(first)} mid={_fk_to_str(mid)} last={_fk_to_str(last)}"))
head, tail = _fk_unpack_splat([99], 1, 0)
print(_fk_to_str(f"head={_fk_to_str(head)} tail={_fk_to_str(tail)}"))
print(_fk_to_str(''))
print(_fk_to_str('── 4. const keyword ──'))
PI = _fk_const_set('PI', 3.14159)
APP_NAME = _fk_const_set('APP_NAME', 'Frankie')
MAX_ITEMS = _fk_const_set('MAX_ITEMS', 100)
print(_fk_to_str(f"{_fk_to_str(APP_NAME)} — PI={_fk_to_str(PI)} max={_fk_to_str(MAX_ITEMS)}"))
area = _fk_arith("_fk_arith('PI', PI, '5.0', 5.0, '*')", _fk_arith('PI', PI, '5.0', 5.0, '*'), '5.0', 5.0, '*')
print(_fk_to_str(f"Circle area r=5: {_fk_to_str(area)}"))
print(_fk_to_str(''))
print(_fk_to_str('── 5. fn.(args) lambda call syntax ──'))
double = (lambda x: _fk_arith('x', x, '2', 2, '*'))
print(_fk_to_str((double)(6)))
def _lambda_1(a, b):
    return _fk_arith('a', a, 'b', b, '+')
add = _lambda_1
print(_fk_to_str((add)(10, 32)))
pipeline = [(lambda x: _fk_arith('x', x, '2', 2, '*')), (lambda x: _fk_arith('x', x, '3', 3, '+')), (lambda x: _fk_arith('x', x, 'x', x, '*'))]
val = 5
_each_recv_2 = pipeline
for f in _each_recv_2:
    val = (f)(val)
else:
    _fk_break_val = _each_recv_2
_each_result_3 = _fk_break_val
_each_result_3
print(_fk_to_str(f"pipeline(5) = {_fk_to_str(val)}"))
print(_fk_to_str(''))
print(_fk_to_str('── 6. json_encode ──'))
data = {'name': 'Alice', 'scores': [95, 87, 92], 'active': True}
raw = json_encode(data)
print(_fk_to_str(raw))
back = json_parse(raw)
print(_fk_to_str(f"round-trip name: {_fk_to_str(_fk_index(back, 'name'))}"))
print(_fk_to_str(''))
print(_fk_to_str('── 7. base64 ──'))
encoded = base64_encode('admin:secret')
print(_fk_to_str(encoded))
print(_fk_to_str(base64_decode(encoded)))
print(_fk_to_str(''))
print(_fk_to_str('── 8. hmac_sign / hmac_verify ──'))
secret = 'my-app-secret'
token = hmac_sign('user_id=42', secret)
print(_fk_to_str(hmac_verify(token, secret)))
print(_fk_to_str(hmac_verify('tampered:deadbeef', secret)))
print(_fk_to_str(''))
print(_fk_to_str('── 9. String#format ──'))
print(_fk_to_str((_fk_str_format('Hello, {name}! You have {count} messages.', {'name': 'Bob', 'count': 3}) if isinstance('Hello, {name}! You have {count} messages.', str) else 'Hello, {name}! You have {count} messages.'.format({'name': 'Bob', 'count': 3}))))
print(_fk_to_str((_fk_str_format('v{major}.{minor}.{patch}', {'major': 1, 'minor': 15, 'patch': 0}) if isinstance('v{major}.{minor}.{patch}', str) else 'v{major}.{minor}.{patch}'.format({'major': 1, 'minor': 15, 'patch': 0}))))
print(_fk_to_str(''))
print(_fk_to_str('── 10. .chars / .bytes ──'))
print(_fk_to_str(_fk_chars('hello')))
print(_fk_to_str(_fk_bytes('ABC')))
vowels = _fk_select(_fk_chars('Frankie'), lambda c: matches(c, '[aeiouAEIOU]'))
print(_fk_to_str(f"vowels in 'Frankie': {_fk_to_str(vowels)}"))
print(_fk_to_str(''))
print(_fk_to_str('── 11. Path helpers ──'))
print(_fk_to_str(path_join('home', 'blag', 'projects', 'frankie')))
print(_fk_to_str(path_basename('/usr/local/bin/frankiec')))
print(_fk_to_str(path_extname('script.fk')))
print(_fk_to_str(path_stem('report.v115.md')))
print(_fk_to_str(''))
print(_fk_to_str('── 12. Date arithmetic ──'))
release = date_from(2026, 4, 17)
print(_fk_to_str(f"v1.15 released: {_fk_to_str((_fk_str_format(release, '%B %d, %Y') if isinstance(release, str) else release.format('%B %d, %Y')))}"))
print(_fk_to_str(f"30 days later:  {_fk_to_str((_fk_str_format(_fk_arith('release', release, '30', 30, '+'), '%B %d, %Y') if isinstance(_fk_arith('release', release, '30', 30, '+'), str) else _fk_arith('release', release, '30', 30, '+').format('%B %d, %Y')))}"))
print(_fk_to_str('Days since v1.14 (approx 90): ' + _fk_to_str(_fk_arith('release', release, "_fk_arith('release', release, '90', 90, '-')", _fk_arith('release', release, '90', 90, '-'), '-'))))
print(_fk_to_str(f"v1.15 > v1.14 date: {_fk_to_str((release > _fk_arith('release', release, '90', 90, '-')))}"))
print(_fk_to_str(''))
print(_fk_to_str('── 13. .zip_with ──'))
names = ['Alice', 'Bob', 'Carol']
scores = [95, 87, 92]
def _zw_fn_4(name, score):
    print(_fk_to_str(f"  {_fk_to_str(name)}: {_fk_to_str(score)}"))
_fk_zip_with(names, scores, _zw_fn_4)
print(_fk_to_str(''))
print(_fk_to_str('── 14. assert_not_nil / assert_in ──'))
assert_not_nil('hello', 'string is not nil')
assert_not_nil(42, 'number is not nil')
assert_in(3, [1, 2, 3, 4, 5], '3 is in range')
assert_in('fk', ['fk', 'py', 'rb'], 'fk is a known extension')
run_tests()
print(_fk_to_str(''))
print(_fk_to_str('╔══════════════════════════════════════════╗'))
print(_fk_to_str('║         Frankie v1.15 — Done! 🧟         ║'))
print(_fk_to_str('╚══════════════════════════════════════════╝'))