# ── Generated by the Frankie Compiler v1.22.3 ─────────────────────────
import math as _math
import sys as _sys
from frankie_stdlib import *

print(_fk_to_str('╔══════════════════════════════════════════╗'))
print(_fk_to_str("║       Frankie v1.12 — What's New         ║"))
print(_fk_to_str('╚══════════════════════════════════════════╝'))
print(_fk_to_str(''))
print(_fk_to_str('── 1. String .gsub with Block ──'))
result = _fk_gsub_with_block('hello world', '[aeiou]', lambda m: m.upper())
print(_fk_to_str(result))
masked = _fk_gsub_with_block('Card: 4111-1111-1111-1111', '\\d', lambda m: '*')
print(_fk_to_str(masked))
lengths = _fk_gsub_with_block('one two three four', '\\w+', lambda m: str(len(m)))
print(_fk_to_str(lengths))
def _gsub_fn_1(m):
    base = (65 if (m == m.upper()) else 97)
    return _fk_chr(_fk_arith('_fk_arith(\'_fk_arith("_fk_arith(\\\'_fk_ord(m)\\\', _fk_ord(m), \\\'base\\\', base, \\\'-\\\')", _fk_arith(\\\'_fk_ord(m)\\\', _fk_ord(m), \\\'base\\\', base, \\\'-\\\'), \\\'13\\\', 13, \\\'+\\\')\', _fk_arith("_fk_arith(\'_fk_ord(m)\', _fk_ord(m), \'base\', base, \'-\')", _fk_arith(\'_fk_ord(m)\', _fk_ord(m), \'base\', base, \'-\'), \'13\', 13, \'+\'), \'26\', 26, \'%\')', _fk_arith('_fk_arith("_fk_arith(\'_fk_ord(m)\', _fk_ord(m), \'base\', base, \'-\')", _fk_arith(\'_fk_ord(m)\', _fk_ord(m), \'base\', base, \'-\'), \'13\', 13, \'+\')', _fk_arith("_fk_arith('_fk_ord(m)', _fk_ord(m), 'base', base, '-')", _fk_arith('_fk_ord(m)', _fk_ord(m), 'base', base, '-'), '13', 13, '+'), '26', 26, '%'), 'base', base, '+'))
rot = _fk_gsub_with_block('Frankie', '[a-zA-Z]', _gsub_fn_1)
print(_fk_to_str(rot))
print(_fk_to_str(''))
print(_fk_to_str('── 2. Hash .map_hash ──'))
prices = {'apple': 1.2, 'banana': 0.5, 'cherry': 3.0}
doubled = _fk_map_hash(prices, lambda k, v: [k, _fk_arith('v', v, '2', 2, '*')])
print(_fk_to_str(doubled))
def _mh_fn_2(k, v):
    discounted = (fk_round(_fk_arith('v', v, '0.9', 0.9, '*'), 2) if (v > 1.0) else v)
    return [k, discounted]
sale = _fk_map_hash(prices, _mh_fn_2)
print(_fk_to_str(sale))
flipped = _fk_map_hash({'a': 1, 'b': 2, 'c': 3}, lambda k, v: [v, str(k)])
print(_fk_to_str(flipped))
config = {'host': 'localhost', 'port': 5432, 'db': 'main'}
upper_config = _fk_map_hash(config, lambda k, v: [str(k).upper(), v])
print(_fk_to_str(upper_config))
print(_fk_to_str(''))
print(_fk_to_str('── 3. round(x, n) ──'))
print(_fk_to_str(fk_round(3.14159, 2)))
print(_fk_to_str(fk_round(2.71828, 3)))
print(_fk_to_str(fk_round(1.5)))
print(_fk_to_str(fk_round(99.999, 1)))
print(_fk_to_str(fk_round((-3.567), 2)))
scores = [87.333, 92.666, 78.999, 95.001]
display = [fk_round(s, 1) for s in scores]
print(_fk_to_str(display))
data = [1.23456, 7.89012, 3.45678]
print(_fk_to_str([fk_round(x, 2) for x in data]))
print(_fk_to_str(''))
print(_fk_to_str('── 4. Vector .product(other) ──'))
print(_fk_to_str(_fk_cartesian_product([1, 2], [3, 4])))
xs = [0, 1, 2]
ys = [0, 1, 2]
grid = _fk_cartesian_product(xs, ys)
print(_fk_to_str(f"Grid size: {_fk_to_str(len(grid))}"))
suits = ['♠', '♥', '♦', '♣']
values = ['A', 'K', 'Q', 'J']
face_cards = _fk_cartesian_product(suits, values)
print(_fk_to_str(f"Face cards: {_fk_to_str(len(face_cards))}"))
print(_fk_to_str((face_cards[0] if face_cards else None)))
print(_fk_to_str((face_cards[-1] if face_cards else None)))
channels = ['R', 'G', 'B']
pairs = _fk_select(_fk_cartesian_product(channels, channels), lambda p: (_fk_index(p, 0) != _fk_index(p, 1)))
print(_fk_to_str(f"Distinct channel pairs: {_fk_to_str(len(pairs))}"))
print(_fk_to_str(''))
print(_fk_to_str('── 5. String .chars ──'))
vowels = _fk_select(_fk_chars('hello world'), lambda c: (c in 'aeiou'))
print(_fk_to_str(vowels))
unique = len(list(dict.fromkeys(_fk_chars('mississippi'))))
print(_fk_to_str(unique))
print(_fk_to_str(''.join([str(_e) for _e in _fk_chars('Frankie')[::-1]])))
_ewo_obj_3 = {}
_ewo_recv_4 = _fk_chars('abracadabra')
for c in (_ewo_recv_4.items() if isinstance(_ewo_recv_4, dict) else _ewo_recv_4):
    if isinstance(_ewo_recv_4, dict): c = list(c)
    h = _ewo_obj_3
    cur = _fk_index(h, c)
    h[c] = _fk_arith('(0 if (cur == None) else cur)', (0 if (cur == None) else cur), '1', 1, '+')
freq = _ewo_obj_3
print(_fk_to_str(freq))
def palindrome_q(s):
    def _blk_fn_5(c):
        (c >= 'a')
        return (c <= 'z')
    clean = ''.join([str(_e) for _e in _fk_select(_fk_chars(s.lower()), _blk_fn_5)])
    return (clean == ''.join([str(_e) for _e in _fk_chars(clean)[::-1]]))

print(_fk_to_str(palindrome_q('racecar')))
print(_fk_to_str(palindrome_q('Frankie')))
print(_fk_to_str(palindrome_q(gsub('A man a plan a canal Panama', ' ', ''))))
print(_fk_to_str(''))
print(_fk_to_str('── 6. each_with_object + Hash ──'))
words = ['apple', 'banana', 'apple', 'cherry', 'banana', 'apple']
_ewo_obj_6 = {}
_ewo_recv_7 = words
for w in (_ewo_recv_7.items() if isinstance(_ewo_recv_7, dict) else _ewo_recv_7):
    if isinstance(_ewo_recv_7, dict): w = list(w)
    h = _ewo_obj_6
    cur = _fk_index(h, w)
    h[w] = _fk_arith('(0 if (cur == None) else cur)', (0 if (cur == None) else cur), '1', 1, '+')
counts = _ewo_obj_6
print(_fk_to_str(counts))
_ewo_obj_8 = {'even': [], 'odd': []}
_ewo_recv_9 = [1, 2, 3, 4, 5, 6]
for n in (_ewo_recv_9.items() if isinstance(_ewo_recv_9, dict) else _ewo_recv_9):
    if isinstance(_ewo_recv_9, dict): n = list(n)
    h = _ewo_obj_8
    if (_fk_arith('n', n, '2', 2, '%') == 0):
        (_fk_list_push(_fk_index(h, 'even'), n))
    else:
        (_fk_list_push(_fk_index(h, 'odd'), n))
grouped = _ewo_obj_8
print(_fk_to_str(grouped))
_ewo_obj_10 = {}
_ewo_recv_11 = [1, 4, 9, 16, 25]
for x in (_ewo_recv_11.items() if isinstance(_ewo_recv_11, dict) else _ewo_recv_11):
    if isinstance(_ewo_recv_11, dict): x = list(x)
    h = _ewo_obj_10
    h[x] = int(_fk_sqrt(x))
lookup = _ewo_obj_10
print(_fk_to_str(lookup))
print(_fk_to_str(''))
print(_fk_to_str('── 7. assert_match / assert_nil ──'))
print(_fk_to_str('(These are test assertions — run with: frankiec test whats_new_v112.fk)'))
print(_fk_to_str(''))
print(_fk_to_str(matches('hello@example.com', '\\w+@\\w+\\.\\w+')))
print(_fk_to_str(matches('not-an-email', '\\w+@\\w+\\.\\w+')))
user = None
print(_fk_to_str(_fk_is_nil(user)))
print(_fk_to_str(''))
print(_fk_to_str('── 8. FileNotFoundError ──'))
try:
    content = file_read('this_file_does_not_exist.txt')
except _fk_exc('FileNotFoundError') as e:
    e = str(e)
    print(_fk_to_str(f"Caught: {_fk_to_str(e)}"))
try:
    lines = file_lines('also_missing.csv')
except _fk_exc('FileNotFoundError') as e:
    e = str(e)
    print(_fk_to_str(f"Caught: {_fk_to_str(e)}"))
print(_fk_to_str(file_exists('missing.txt')))
print(_fk_to_str(file_delete('missing.txt')))
print(_fk_to_str(''))
print(_fk_to_str('── All v1.12 features demonstrated ──'))
print(_fk_to_str('Run with: frankiec run whats_new_v112.fk'))